import pandas as pd
import numpy as np
import functions.data_transformations as data_transformations
import functions.data_smells as data_smells
from helpers.enumerations import Belong, Operator, Operation, SpecialType, DataType, DerivedType, Closure, FilterType, MapOperation, MathOperator
from helpers.logger import set_logger
import pyarrow
from functions.PMML import PMMLModel

def generateWorkflow():
	#-----------------New DataProcessing-----------------
	columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df=pd.read_parquet('/wf_validation_python/data/output/columnFilter_input_dataDictionary.parquet')

	
	common_invalid_list=['inf', '-inf', 'nan']
	common_missing_list=['', '?', '.','null','none','na']
	
	list_missing=[]
	list_invalid=[]
	
	data_smells.check_missing_invalid_value_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, 
														missing_invalid_list=[], common_missing_invalid_list=common_missing_list, field='Airline')
	list_missing=[]
	list_invalid=[]
	
	data_smells.check_missing_invalid_value_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, 
														missing_invalid_list=[], common_missing_invalid_list=common_missing_list, field='Airline ID')
	list_missing=[]
	list_invalid=[]
	
	data_smells.check_missing_invalid_value_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, 
														missing_invalid_list=[], common_missing_invalid_list=common_missing_list, field='Source airport')
	list_missing=[]
	list_invalid=[]
	
	data_smells.check_missing_invalid_value_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, 
														missing_invalid_list=[], common_missing_invalid_list=common_missing_list, field='Source airport ID')
	list_missing=[]
	list_invalid=[]
	
	data_smells.check_missing_invalid_value_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, 
														missing_invalid_list=[], common_missing_invalid_list=common_missing_list, field='Destination airport')
	list_missing=[]
	list_invalid=[]
	
	data_smells.check_missing_invalid_value_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, 
														missing_invalid_list=[], common_missing_invalid_list=common_missing_list, field='Destination airport ID')
	list_missing=[]
	list_invalid=[]
	
	data_smells.check_missing_invalid_value_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, 
														missing_invalid_list=[], common_missing_invalid_list=common_missing_list, field='Codeshare')
	list_missing=[]
	list_invalid=[]
	
	data_smells.check_missing_invalid_value_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, 
														missing_invalid_list=[], common_missing_invalid_list=common_missing_list, field='Stops')
	list_missing=[]
	list_invalid=[]
	
	data_smells.check_missing_invalid_value_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, 
														missing_invalid_list=[], common_missing_invalid_list=common_missing_list, field='Equipment')
	
	data_smells.check_integer_as_floating_point(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline')
	data_smells.check_integer_as_floating_point(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline ID')
	data_smells.check_integer_as_floating_point(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport')
	data_smells.check_integer_as_floating_point(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport ID')
	data_smells.check_integer_as_floating_point(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport')
	data_smells.check_integer_as_floating_point(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport ID')
	data_smells.check_integer_as_floating_point(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Codeshare')
	data_smells.check_integer_as_floating_point(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Stops')
	data_smells.check_integer_as_floating_point(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Equipment')
	
	data_smells.check_types_as_string(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline', expected_type=DataType.STRING)
	data_smells.check_types_as_string(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline ID', expected_type=DataType.STRING)
	data_smells.check_types_as_string(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport', expected_type=DataType.STRING)
	data_smells.check_types_as_string(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport ID', expected_type=DataType.STRING)
	data_smells.check_types_as_string(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport', expected_type=DataType.STRING)
	data_smells.check_types_as_string(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport ID', expected_type=DataType.STRING)
	data_smells.check_types_as_string(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Codeshare', expected_type=DataType.STRING)
	data_smells.check_types_as_string(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Stops', expected_type=DataType.STRING)
	data_smells.check_types_as_string(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Equipment', expected_type=DataType.STRING)
	
	data_smells.check_special_character_spacing(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline')
	data_smells.check_special_character_spacing(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline ID')
	data_smells.check_special_character_spacing(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport')
	data_smells.check_special_character_spacing(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport ID')
	data_smells.check_special_character_spacing(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport')
	data_smells.check_special_character_spacing(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport ID')
	data_smells.check_special_character_spacing(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Codeshare')
	data_smells.check_special_character_spacing(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Stops')
	data_smells.check_special_character_spacing(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Equipment')
	
	data_smells.check_suspect_precision(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline')
	data_smells.check_suspect_precision(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline ID')
	data_smells.check_suspect_precision(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport')
	data_smells.check_suspect_precision(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport ID')
	data_smells.check_suspect_precision(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport')
	data_smells.check_suspect_precision(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport ID')
	data_smells.check_suspect_precision(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Codeshare')
	data_smells.check_suspect_precision(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Stops')
	data_smells.check_suspect_precision(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Equipment')
	
	
	data_smells.check_date_as_datetime(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline')
	data_smells.check_date_as_datetime(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline ID')
	data_smells.check_date_as_datetime(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport')
	data_smells.check_date_as_datetime(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport ID')
	data_smells.check_date_as_datetime(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport')
	data_smells.check_date_as_datetime(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport ID')
	data_smells.check_date_as_datetime(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Codeshare')
	data_smells.check_date_as_datetime(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Stops')
	data_smells.check_date_as_datetime(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Equipment')
	
	data_smells.check_separating_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, decimal_sep='.',  field='Airline')
	data_smells.check_separating_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, decimal_sep='.',  field='Airline ID')
	data_smells.check_separating_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, decimal_sep='.',  field='Source airport')
	data_smells.check_separating_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, decimal_sep='.',  field='Source airport ID')
	data_smells.check_separating_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, decimal_sep='.',  field='Destination airport')
	data_smells.check_separating_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, decimal_sep='.',  field='Destination airport ID')
	data_smells.check_separating_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, decimal_sep='.',  field='Codeshare')
	data_smells.check_separating_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, decimal_sep='.',  field='Stops')
	data_smells.check_separating_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, decimal_sep='.',  field='Equipment')
	
	
	data_smells.check_ambiguous_datetime_format(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline')
	data_smells.check_ambiguous_datetime_format(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline ID')
	data_smells.check_ambiguous_datetime_format(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport')
	data_smells.check_ambiguous_datetime_format(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport ID')
	data_smells.check_ambiguous_datetime_format(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport')
	data_smells.check_ambiguous_datetime_format(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport ID')
	data_smells.check_ambiguous_datetime_format(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Codeshare')
	data_smells.check_ambiguous_datetime_format(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Stops')
	data_smells.check_ambiguous_datetime_format(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Equipment')
	
	

	columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_transformed=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df.copy()
	field_list_columnFilter_param_field=['Airline', 'Airline ID', 'Source airport', 'Source airport ID', 'Destination airport', 'Destination airport ID', 'Codeshare', 'Stops', 'Equipment']
	columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_transformed=data_transformations.transform_filter_columns(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_transformed,
																	columns=field_list_columnFilter_param_field, belong_op=Belong.NOTBELONG)
	
	columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__output_dataDictionary_df=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_transformed
	columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__output_dataDictionary_df.to_parquet('/wf_validation_python/data/output/columnFilter_output_dataDictionary.parquet')
	columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__output_dataDictionary_df=pd.read_parquet('/wf_validation_python/data/output/columnFilter_output_dataDictionary.parquet')
	

set_logger("transformations")
generateWorkflow()
